### ISSUE TITLE
it cant works in deepin os.

### ISSUE THREAD

**Issue by Talon001** [ilnanny/TL-WN725N-TP-Link-Debian#1]
HI !
thank for your tp-link drivers.i follow your readme to install the driver , but it cant works on my deepinos which is based on debian.
may you write your readme more detailed？

sorry for my poor english

**Comment by donlaiq** [comment]
I did an upgrade to Debian 9.3 and the tp-link drivers don't work anymore. Did you tried it with Debian 9.3?

**Comment by ilnanny** [comment]
Update and fix
