### ISSUE TITLE
Not working on Dietpi Stretch (NanoPi M1) with TL-WN725N 0bda:8179 Realtek Semiconductor Corp. RTL8188EUS

### ISSUE THREAD

**Issue by benben8888** [ilnanny/TL-WN725N-TP-Link-Debian#2]
Hi,

I am using Dietpi Nanopi M1 "Linux DietPi 4.14.0 #83 SMP Fri Dec 8 17:44:19 CST 2017 armv7l GNU/Linux".

I followed as per described to install my newly bought TL-WN725N 0bda:8179 Realtek Semiconductor Corp. RTL8188EUS, unfortunately it doesn't work.

```
apt-get update
apt-get install linux-headers-$(uname -r)
apt-get update
apt-get install build-essential
git clone https://github.com/ilnanny/TL-WN725N-TP-Link-Debian.git
cd TL-WN725N-TP-Link-Debian
make all
su
make install
insmod 8188eu.ko
ifconfig (check to see if your wireless wlan cards is now listed)
reboot
```

The installation goes smooth at the beginning and stuck at "make all" with the error of:-

> make ARCH=arm CROSS_COMPILE= -C /lib/modules/4.14.0/build M=/root/TL-WN725N-TP-Link-Debian  modules
> make[1]: *** /lib/modules/4.14.0/build: No such file or directory.  Stop.
> Makefile:147: recipe for target 'modules' failed
> make: *** [modules] Error 2
> root@DietPi:~/TL-WN725N-TP-Link-Debian#

Then nothing I can go further. I hope some experts can assist me on this matter asap. Thank you in advance.

Regards.

**Comment by ilnanny** [comment]
==
apt install build-essential 
==
please try installing on a kernel other than 4.14.
this type of installation is tested on a stable kernel with debian patches.
If you have manually compiled the kernel, you must enable the drivers.

**Comment by benben8888** [comment]
Hi ilnanny,

Below is the result.

```
root@DietPi:~# apt install build-essential
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@DietPi:~#
```

**Installing on a kernel other than 4.1.4:-
Is it tried to install on old kernel like debian jessie or so ...

Anyway, I am newbie on using linux / debian.

Thank you for the advise.

**Comment by ilnanny** [comment]
update and fix all error
