### ISSUE TITLE
make install error: cp: cannot create regular file '/lib/firmware/.':No such file or directory

### ISSUE THREAD

**Issue by ahm-essam** [ilnanny/TL-WN725N-TP-Link-Debian#3]
I got the following error at stage "make install" on a freshly installed debian 9 stretch:

`cp: cannot create regular file '/lib/firmware/.':No such file or directory`

Creating the directory `/lib/firmware` fixes the error and the driver works fine after that. I think the install script should contain a condition to create the directory if not existed. 

Took me some googling to fix it, thought of making this issue to save someone time and hoping for the developer to make a new commit with the fix.

Thank you

**Comment by ilnanny** [comment]
you can contribute yourself by fix the file and pull

**Comment by ahm-essam** [comment]
Done! Merge and close this issue
