### ISSUE TITLE
Mint 4.15 build problem. 

### ISSUE THREAD

**Issue by progrdk** [ilnanny/TL-WN725N-TP-Link-Debian#5]
Is it possible to compile this driver on Mint 4.15.0-20-generic with gcc 7.3.0?
On 'sudo make' I'm getting this :

make ARCH=x86_64 CROSS_COMPILE= -C
/lib/modules/4.15.0-20-generic/build
M=/home/TL-WN725N-TP-Link-Debian-master  modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-20-generic'
  CC [M]  /home/TL-WN725N-TP-Link-Debian-master/core/rtw_ap.o
In file included from /home/TL-WN725N-TP-Link-Debian-master/core/rtw_ap.c:22:0:
/home/TL-WN725N-TP-Link-Debian-master/include/osdep_service.h: In
function ‘_init_timer’:
/home/TL-WN725N-TP-Link-Debian-master/include/osdep_service.h:94:8:
error: ‘struct timer_list’ has no member named ‘data’
  ptimer->data = (unsigned long)cntx;
        ^~
/home/TL-WN725N-TP-Link-Debian-master/include/osdep_service.h:95:2:
error: implicit declaration of function ‘init_timer’; did you mean
‘_init_timer’? [-Werror=implicit-function-declaration]
  init_timer(ptimer);
  ^~~~~~~~~~
  _init_timer
/home/TL-WN725N-TP-Link-Debian-master/include/osdep_service.h: In
function ‘thread_enter’:
/home/TL-WN725N-TP-Link-Debian-master/include/osdep_service.h:287:2:
error: implicit declaration of function ‘allow_signal’; did you mean
‘do_signal’? [-Werror=implicit-function-declaration]
  allow_signal(SIGTERM);
  ^~~~~~~~~~~~
  do_signal
/home/TL-WN725N-TP-Link-Debian-master/include/osdep_service.h: In
function ‘flush_signals_thread’:
/home/TL-WN725N-TP-Link-Debian-master/include/osdep_service.h:292:6:
error: implicit declaration of function ‘signal_pending’; did you mean
‘timer_pending’? [-Werror=implicit-function-declaration]
  if (signal_pending (current))
      ^~~~~~~~~~~~~~
      timer_pending
/home/TL-WN725N-TP-Link-Debian-master/include/osdep_service.h:293:3:
error: implicit declaration of function ‘flush_signals’; did you mean
‘do_signal’? [-Werror=implicit-function-declaration]
   flush_signals(current);
   ^~~~~~~~~~~~~
   do_signal
cc1: some warnings being treated as errors
scripts/Makefile.build:332: recipe for target
'/home/TL-WN725N-TP-Link-Debian-master/core/rtw_ap.o' failed
make[2]: *** [/home/TL-WN725N-TP-Link-Debian-master/core/rtw_ap.o] Error 1
Makefile:1552: recipe for target
'_module_/home/TL-WN725N-TP-Link-Debian-master' failed
make[1]: *** [_module_/home/TL-WN725N-TP-Link-Debian-master] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-20-generic'
Makefile:147: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by ilnanny** [comment]
please don't use 4.15.xx kernel

**Comment by progrdk** [comment]
So, I'll have to stick to 4.4.3 kernel until TP-Link provides a new driver?
Pity...

**Comment by ilnanny** [comment]
First
apt update
apt install linux-headers-$(uname -r)
apt install build-essential

**Comment by vardhannaik** [comment]
I made the below changes and then it worked for me for kernel 4.19. Ptimer seems to be called via timer_Setup
File osdep_service.h
static inline void _init_timer(struct timer_list	 *ptimer,struct  net_device *nic_hdl,void *pfunc,void* cntx)
{
	//ptimer->function = pfunc;
//	ptimer->data = (unsigned long)cntx;
	//init_timer(ptimer);
	//timer_setup(&dev->getIntrTimer, GetIntrTimerCallback, 0);
	timer_setup(ptimer, pfunc, 0);
}

Second unrelated was the rtw_select_queue variable.
File os_intfs.c
#if (LINUX_VERSION_CODE>=KERNEL_VERSION(5,2,0))
static u16 rtw_select_queue(struct net_device *dev, struct sk_buff *skb,
			    struct net_device *sb_dev)
#elif (LINUX_VERSION_CODE>=KERNEL_VERSION(4,19,0))
static u16 rtw_select_queue(struct net_device *dev, struct sk_buff *skb,
			    struct net_device *sb_dev,
			    select_queue_fallback_t fallback)
#elif (LINUX_VERSION_CODE>=KERNEL_VERSION(3,14,0))
static u16 rtw_select_queue(struct net_device *dev, struct sk_buff *skb,
			    void *accel_priv,
			    select_queue_fallback_t fallback)
#else
static u16 rtw_select_queue(struct net_device *dev, struct sk_buff *skb)
#endif

/* VN
static u16 rtw_select_queue(struct net_device *dev, struct sk_buff *skb
#if (LINUX_VERSION_CODE >= KERNEL_VERSION(3, 14, 0))
			    ,void *unused
                            ,select_queue_fallback_t fallback
#elif (LINUX_VERSION_CODE == KERNEL_VERSION(3, 13, 0))
			    , void *accel
#endif
)

*/
