### ISSUE TITLE
insmod: ERROR: could not insert module 8188eu.ko: Invalid module format

### ISSUE THREAD

**Issue by dark0ghost** [ilnanny/TL-WN725N-TP-Link-Debian#9]
:~/TL-WN725N-TP-Link-Debian# insmod 8188eu.ko
insmod: ERROR: could not insert module 8188eu.ko: Invalid module format

**Comment by Hiv6** [comment]
me too , did you resolved this?

**Comment by dark0ghost** [comment]
Yes, I reboot system and drive work

**Comment by Hiv6** [comment]
Lol thx
